### ISSUE TITLE
Restart due to user deleting account

### ISSUE THREAD

**Issue by NorthernMan54** [NorthernMan54/alexaAwsBackend#91]
Mar 14 22:42:31 ip-172-26-1-254 startup[803]: mqtt message:  command/ascomtech/1 {"directive":{"header":{"namespace":"Alexa.Discovery","name":"Discover
Mar 14 22:42:31 ip-172-26-1-254 startup[803]: getUser Error:  null
Mar 14 22:42:31 ip-172-26-1-254 startup[803]: events.js:174
Mar 14 22:42:31 ip-172-26-1-254 startup[803]:       throw er; // Unhandled 'error' event
Mar 14 22:42:31 ip-172-26-1-254 startup[803]:       ^
Mar 14 22:42:31 ip-172-26-1-254 startup[803]: TypeError: Cannot read property 'topics' of null
Mar 14 22:42:31 ip-172-26-1-254 startup[803]:     at /home/ubuntu/awsWeb/lib/utility.js:25:22
Mar 14 22:42:31 ip-172-26-1-254 startup[803]:     at immediate (/home/ubuntu/awsWeb/node_modules/mongoose/lib/model.js:5074:18)
Mar 14 22:42:31 ip-172-26-1-254 startup[803]:     at process._tickCallback (internal/process/next_tick.js:61:11)
Mar 14 22:42:31 ip-172-26-1-254 startup[803]: Emitted 'error' event at:
Mar 14 22:42:31 ip-172-26-1-254 startup[803]:     at immediate (/home/ubuntu/awsWeb/node_modules/mongoose/lib/model.js:5076:15)
Mar 14 22:42:31 ip-172-26-1-254 startup[803]:     at process._tickCallback (internal/process/next_tick.js:61:11)
Mar 14 22:42:31 ip-172-26-1-254 systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Mar 14 22:42:31 ip-172-26-1-254 systemd[1]: homebridge.service: Unit entered failed state.
Mar 14 22:42:31 ip-172-26-1-254 systemd[1]: homebridge.service: Failed with result 'exit-code'.

**Comment by NorthernMan54** [comment]
```
Mar 20 22:54:07 ip-172-26-1-254 startup[7728]: getUser Error:  null
Mar 20 22:54:07 ip-172-26-1-254 startup[7728]: events.js:174
Mar 20 22:54:07 ip-172-26-1-254 startup[7728]:       throw er; // Unhandled 'error' event
Mar 20 22:54:07 ip-172-26-1-254 startup[7728]:       ^
Mar 20 22:54:07 ip-172-26-1-254 startup[7728]: TypeError: Cannot read property 'created' of null
Mar 20 22:54:07 ip-172-26-1-254 startup[7728]:     at /home/ubuntu/awsWeb/lib/usage.js:102:27
Mar 20 22:54:07 ip-172-26-1-254 startup[7728]:     at immediate (/home/ubuntu/awsWeb/node_modules/mongoose/lib/model.js:5074:18)
Mar 20 22:54:07 ip-172-26-1-254 startup[7728]:     at process._tickCallback (internal/process/next_tick.js:61:11)
Mar 20 22:54:07 ip-172-26-1-254 startup[7728]: Emitted 'error' event at:
Mar 20 22:54:07 ip-172-26-1-254 startup[7728]:     at immediate (/home/ubuntu/awsWeb/node_modules/mongoose/lib/model.js:5076:15)
Mar 20 22:54:07 ip-172-26-1-254 startup[7728]:     at process._tickCallback (internal/process/next_tick.js:61:11)
Mar 20 22:54:07 ip-172-26-1-254 systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by NorthernMan54** [comment]
```
Mar 23 16:27:52 ip-172-26-1-254 startup[21515]: mqtt message:  event/cdrawdy/1 {"context":{},"event":{"header":{"messageId":"2cdb68fb-48ae-4107-a57c-
Mar 23 16:27:52 ip-172-26-1-254 startup[21515]: Sending event:  cdrawdy https://api.amazonalexa.com/v3/events [object Object]
Mar 23 16:27:52 ip-172-26-1-254 startup[21515]: events.js:174
Mar 23 16:27:52 ip-172-26-1-254 startup[21515]:       throw er; // Unhandled 'error' event
Mar 23 16:27:52 ip-172-26-1-254 startup[21515]:       ^
Mar 23 16:27:52 ip-172-26-1-254 startup[21515]: TypeError: Cannot read property 'username' of null
Mar 23 16:27:52 ip-172-26-1-254 startup[21515]:     at /home/ubuntu/awsWeb/lib/oauthClient.js:31:68
Mar 23 16:27:52 ip-172-26-1-254 startup[21515]:     at immediate (/home/ubuntu/awsWeb/node_modules/mongoose/lib/model.js:5074:18)
Mar 23 16:27:52 ip-172-26-1-254 startup[21515]:     at process._tickCallback (internal/process/next_tick.js:61:11)
Mar 23 16:27:52 ip-172-26-1-254 startup[21515]: Emitted 'error' event at:
Mar 23 16:27:52 ip-172-26-1-254 startup[21515]:     at immediate (/home/ubuntu/awsWeb/node_modules/mongoose/lib/model.js:5076:15)
Mar 23 16:27:52 ip-172-26-1-254 startup[21515]:     at process._tickCallback (internal/process/next_tick.js:61:11)
Mar 23 16:27:52 ip-172-26-1-254 systemd[1]: homebridge.service: Main process exited, code=exited, status=1/FAILURE
Mar 23 16:27:52 ip-172-26-1-254 systemd[1]: homebridge.service: Unit entered failed state.
Mar 23 16:27:52 ip-172-26-1-254 systemd[1]: homebridge.service: Failed with result 'exit-code'.
Mar 23 16:28:01 ip-172-26-1-254 CRON[2784]: (root) CMD (/etc/cron.d/afraid.aws.sh >/dev/null)
```
